rly_file = "Shrewsbury.rly"
ttb_files = [ "Fri_18_11_2022_0600.ttb",]
img_files = [ "Shrewsbury.bmp",]
doc_files = [ "README.md",]
release_date = "2022-11-20"
version = "1.0.0"
country_code = "GB"
year = "2022"
factual = true
description = "Simulation of Shrewsbury railway station in Shropshire, UK"
display_name = "Shrewsbury, UK"
name = "Shrewsbury"
author = "Krizar"
contributors = []
ssn_files = [ "Shrewsbury_Fri_18_11_2022_0600.ssn",]
